### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by andreasdc** [starlis/empirecraft#13]
Are you sure Optimize-Entity-and-Tile-Entity-Removal patch gives performance boost? From the profilers it appears that it has higher percentage.

**Comment by chickeneer** [comment]
That patch has not been in use since 1.16. Whether it helped performance before then - I don't really care to explore. That patch is not in a usable state in current Minecraft.

**Comment by andreasdc** [comment]
> That patch has not been in use since 1.16. Whether it helped performance before then - I don't really care to explore. That patch is not in a usable state in current Minecraft.

I'm trying to port it to 1.8, but I'm not sure if it's better than normal implementation.

**Comment by chickeneer** [comment]
I stand corrected. It hasn't been in use since 1.8 (created and removed in 1.8). It is worth noting that it was intentionally removed.
https://github.com/starlis/empirecraft/commit/b881545d55fa3d26fa2043488d9a859b0078601b

I will say. That you are not going to get the answer that you seek here. There would not have been any official profiler data.
From my understanding, this patch would have improved 'something' when it was written back then - but part of that could be server configuration dependent, not necessarily something to apply to all situations. There is probably a reason it didn't propagate upstream nor receive further to use further. Empirecraft was always a testing ground before sending patches elsewhere.

**Comment by andreasdc** [comment]
> I stand corrected. It hasn't been in use since 1.8 (created and removed in 1.8). It is worth noting that it was intentionally removed. [b881545](https://github.com/starlis/empirecraft/commit/b881545d55fa3d26fa2043488d9a859b0078601b)
> 
> I will say. That you are not going to get the answer that you seek here. There would not have been any official profiler data. From my understanding, this patch would have improved 'something' when it was written back then - but part of that could be server configuration dependent, not necessarily something to apply to all situations. There is probably a reason it didn't propagate upstream nor receive further to use further. Empirecraft was always a testing ground before sending patches elsewhere.

Thanks, I will investigate. Do you know some hacks to improve exploding big chunks of tnt?
