### ISSUE TITLE
0007-Fix-PlayerInteractEvent-for-Armor-Stands.patch appears to be merged by upstream.

### ISSUE THREAD

**Issue by ryantheleach** [starlis/empirecraft#7]

**Comment by chickeneer** [comment]
I believe you misunderstood the purpose of this patch. It collapses the `PlayerInteractAtEntityEvent` and `PlayerInteractEntityEvent` into the same HandlerList. So that they both will go through the same Listener. 

The patch has not been merged upstream because it doesn't belong in upstream.

A friendly reminder that Empirecraft patches which are tagged `// EMC` are not designed to go upstream. But more of patches which allow us to change how our server alone works.

Let me know if I misunderstood your understanding.

**Comment by ryantheleach** [comment]
I believe I misread the patch, and didn't notice it was commenting a section out. Apologies for the invalid report.
